"""One-off analysis driver: compare the homepage-only collection pass
(archived in output/briefs_pass1_homepage/) with the deeper-page pass
(output/briefs/) and write docs/DEEP_COLLECTION.md.

This is the experiment docs/FINDINGS.md proposed after the first run: does
reaching past the homepage (careers, technology/integrations, press,
services pages) let the rubric's operational components fire, and does it
change which workflows get hypothesised? Everything here is derived
offline from committed briefs; no pages are fetched and no model is called.
Not a CLI subcommand (CLAUDE.md R17).
"""

from __future__ import annotations

import csv
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from trelium_gtm.coverage import compute_coverage  # noqa: E402
from trelium_gtm.models import AccountBrief  # noqa: E402
from trelium_gtm.ranking import rank  # noqa: E402
from trelium_gtm.taxonomy import WorkflowID  # noqa: E402
from trelium_gtm.validate import ablate, spearman_rho  # noqa: E402

PASS1_DIR = REPO_ROOT / "output" / "briefs_pass1_homepage"
PASS2_DIR = REPO_ROOT / "output" / "briefs"
PROSPECTS_CSV = REPO_ROOT / "data" / "prospects.csv"
OUT_PATH = REPO_ROOT / "docs" / "DEEP_COLLECTION.md"

COMPONENT_LABELS = {
    "c1": "core vertical fit",
    "c2": "operational complexity",
    "c3": "software/ecosystem",
    "c4": "scale",
    "c5": "growth/buying trigger",
    "c6": "evidence quality",
}


def load(dir_path: Path) -> dict[str, AccountBrief]:
    briefs = {}
    for path in sorted(dir_path.glob("*.json")):
        b = AccountBrief.model_validate_json(path.read_text(encoding="utf-8"))
        briefs[b.domain] = b
    return briefs


def report_order() -> list[str]:
    with PROSPECTS_CSV.open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    rows.sort(key=lambda r: int(r["priority"]))
    return [r["company"].strip() for r in rows]


def pages_with_evidence(b: AccountBrief) -> int:
    return len({e.source_url for e in b.evidence})


def failed_pages(b: AccountBrief) -> int:
    return sum(1 for g in b.research_gaps if g.startswith("Failed to collect "))


def pages_read(b: AccountBrief) -> int:
    """Pages that yielded a fact plus pages recorded as read with zero yield.
    Pass-1 briefs predate the zero-yield gap line, so for them this equals
    pages_with_evidence (a lower bound)."""
    return pages_with_evidence(b) + sum(1 for g in b.research_gaps if g.startswith("Read "))


def workflows(b: AccountBrief) -> list[str]:
    return sorted({wh.workflow_id.value.removeprefix("WF_") for wh in b.workflow_hypotheses})


def score_str(b: AccountBrief) -> str:
    return str(b.score.total) if b.score.status == "SCORED" else b.score.status.replace("_", " ").lower()


def fired_components(b: AccountBrief) -> str:
    if b.score.status != "SCORED":
        return "-"
    fired = [k for k, v in b.score.components.items() if v > 0]
    return ", ".join(fired) or "none"


def _sort_key(p2: dict[str, AccountBrief], d: str):
    b = p2.get(d)
    if b is not None and b.score.status == "SCORED":
        return (0, -(b.score.total or 0), d)
    return (1, 0, d)


def main() -> None:
    p1 = load(PASS1_DIR)
    p2 = load(PASS2_DIR)
    domains = sorted(set(p1) | set(p2), key=lambda d: _sort_key(p2, d))

    order = report_order()
    ranked2 = rank(list(p2.values()))
    scored2 = [b for b in ranked2 if b.score.status == "SCORED"]
    scored1 = [b for b in rank(list(p1.values())) if b.score.status == "SCORED"]
    rho2 = spearman_rho([b.company for b in scored2], order)
    rho1 = spearman_rho([b.company for b in scored1], order)

    lines: list[str] = []
    lines.append("# Deeper-page collection: pass 2 versus the homepage-only baseline\n")
    lines.append(
        "`docs/FINDINGS.md` (finding B) predicted that the rubric's four operational components "
        "(c2 operational complexity, c3 named systems, c4 scale, c5 growth triggers) could not fire "
        "from homepage-level evidence, and proposed extending collection to careers, "
        "technology/integrations and press pages as the first experiment. This document is that "
        "experiment. Pass 1 (archived in `output/briefs_pass1_homepage/`) collected the homepage "
        "plus at most one about page and one careers page. Pass 2 (`output/briefs/`) adds one "
        "technology/integrations page, one press/news page and one services/capabilities page, "
        "discovered from the homepage's own navigation, at most six requests per account. "
        "Same extraction prompts, same scorer, same taxonomy; the only change is what was read.\n"
    )
    lines.append("Generated by `scripts/compare_passes.py` from committed briefs; no fetches, no model calls.\n")

    # ---- headline counts -------------------------------------------------
    def counts(briefs: dict[str, AccountBrief]) -> Counter:
        c: Counter = Counter()
        for b in briefs.values():
            c["scored"] += b.score.status == "SCORED"
            c["insufficient"] += b.score.status == "INSUFFICIENT_EVIDENCE"
            c["out_of_icp"] += b.score.status == "OUT_OF_ICP"
            c["facts"] += len(b.facts)
            c["pages"] += pages_with_evidence(b)
            c["pages_read"] += pages_read(b)
            c["hyps"] += len(b.workflow_hypotheses)
            c["with_hyp"] += bool(b.workflow_hypotheses)
            if b.score.status == "SCORED":
                for k, v in (b.score.components or {}).items():
                    if v > 0:
                        c[f"fired_{k}"] += 1
        return c

    c1, c2 = counts(p1), counts(p2)
    lines.append("## Headline\n")
    lines.append("| Measure | Pass 1 (homepage-only) | Pass 2 (deeper pages) |")
    lines.append("|---|---|---|")
    lines.append(f"| Accounts scored | {c1['scored']} / {len(p1)} | {c2['scored']} / {len(p2)} |")
    lines.append(f"| Accounts with insufficient evidence | {c1['insufficient']} | {c2['insufficient']} |")
    lines.append(f"| Accounts gated OUT_OF_ICP | {c1['out_of_icp']} | {c2['out_of_icp']} |")
    lines.append(f"| Pages read (pass 1 is a lower bound, see below) | {c1['pages_read']} | {c2['pages_read']} |")
    lines.append(f"| Pages that yielded at least one verified fact | {c1['pages']} | {c2['pages']} |")
    lines.append(f"| Verified facts (total) | {c1['facts']} | {c2['facts']} |")
    lines.append(f"| Accounts with at least one workflow hypothesis | {c1['with_hyp']} | {c2['with_hyp']} |")
    lines.append(f"| Workflow hypotheses (total) | {c1['hyps']} | {c2['hyps']} |")
    for k, label in COMPONENT_LABELS.items():
        lines.append(f"| Scored accounts where {k} ({label}) > 0 | {c1[f'fired_{k}']} | {c2[f'fired_{k}']} |")
    top1 = scored1[0] if scored1 else None
    top2 = scored2[0] if scored2 else None
    lines.append(
        f"| Highest score | {top1.score.total if top1 else '-'} ({top1.company if top1 else '-'}) | "
        f"{top2.score.total if top2 else '-'} ({top2.company if top2 else '-'}) |"
    )
    lines.append(
        f"| Spearman rho vs. report priority order (scored accounts) | "
        f"{'%.3f' % rho1 if rho1 is not None else 'n/a'} (n={len(scored1)}) | "
        f"{'%.3f' % rho2 if rho2 is not None else 'n/a'} (n={len(scored2)}) |"
    )
    lines.append("")

    # ---- per-account table ---------------------------------------------
    lines.append("## Per account\n")
    lines.append(
        "Pages = URLs that produced at least one verified fact / URLs read at all (pass-1 briefs "
        "did not record zero-yield pages, so their second number is a lower bound); failed = pages "
        "the collector could not read (robots.txt, HTTP error, no visible text). Workflows are the "
        "hypothesised taxonomy ids without the `WF_` prefix.\n"
    )
    lines.append(
        "| Company | P1 score | P2 score | P1 pages w/ facts / read (failed) | "
        "P2 pages w/ facts / read (failed) | P1 facts | P2 facts | P2 components > 0 | "
        "P1 workflows | P2 workflows |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for d in domains:
        a, b = p1.get(d), p2.get(d)
        name = (b or a).company
        lines.append(
            f"| {name} | {score_str(a) if a else '-'} | {score_str(b) if b else '-'} | "
            f"{pages_with_evidence(a) if a else '-'} / {pages_read(a) if a else '-'} ({failed_pages(a) if a else '-'}) | "
            f"{pages_with_evidence(b) if b else '-'} / {pages_read(b) if b else '-'} ({failed_pages(b) if b else '-'}) | "
            f"{len(a.facts) if a else '-'} | {len(b.facts) if b else '-'} | "
            f"{fired_components(b) if b else '-'} | "
            f"{', '.join(workflows(a)) if a and workflows(a) else '-'} | "
            f"{', '.join(workflows(b)) if b and workflows(b) else '-'} |"
        )
    lines.append("")

    # ---- coverage --------------------------------------------------------
    lines.append("## Workflow coverage (scored accounts)\n")
    cov1 = {r.workflow_id: r for r in compute_coverage(scored1)}
    cov2 = {r.workflow_id: r for r in compute_coverage(scored2)}
    lines.append("| Workflow | Trelium agent | Pass 1 count | Pass 2 count | Pass 2 examples |")
    lines.append("|---|---|---|---|---|")
    for wf in sorted(WorkflowID, key=lambda w: (-cov2[w].total_count, w.value)):
        lines.append(
            f"| {wf.value} | {cov2[wf].trelium_agent} | {cov1[wf].total_count} | {cov2[wf].total_count} | "
            f"{', '.join(cov2[wf].example_companies) or '-'} |"
        )
    lines.append("")

    # ---- ablation --------------------------------------------------------
    lines.append("## Component ablation (top-10 movement)\n")
    lines.append(
        "Each row zeroes one component across the scored accounts of that pass and counts how "
        "many of the original top 10 fall out.\n"
    )
    lines.append("| Component zeroed | Pass 1 | Pass 2 |")
    lines.append("|---|---|---|")
    abl1 = {r.zeroed_component: r.movement_count for r in ablate(scored1, top_n=10)}
    abl2 = {r.zeroed_component: r.movement_count for r in ablate(scored2, top_n=10)}
    for k, label in COMPONENT_LABELS.items():
        lines.append(f"| {k} ({label}) | {abl1.get(k, 0)} | {abl2.get(k, 0)} |")
    lines.append("")

    # ---- collection failure breakdown ------------------------------------
    lines.append("## Collection failures in pass 2\n")
    reasons: Counter = Counter()
    for b in p2.values():
        for g in b.research_gaps:
            if g.startswith("Failed to collect "):
                reason = g.split(": ", 1)[1] if ": " in g else g
                if reason.startswith("Fetch failed"):
                    code = reason.split("'")[1] if "'" in reason else "other"
                    reason = f"Fetch failed ({code.split(' ')[0]})"
                reasons[reason] += 1
    lines.append("| Reason | Page failures |")
    lines.append("|---|---|")
    for reason, n in reasons.most_common():
        lines.append(f"| {reason} | {n} |")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    print(f"pass1 scored={c1['scored']} facts={c1['facts']} hyps={c1['hyps']} rho={rho1}")
    print(f"pass2 scored={c2['scored']} facts={c2['facts']} hyps={c2['hyps']} rho={rho2}")


if __name__ == "__main__":
    main()
